project_name: hall
dist: build/
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: .
    binary: hall
    flags:
      - -tags=lang_zh
      - -v
      - -trimpath
    ldflags:
     - -s -w -X main.BUILDDATE={{.Date}} -X main.VERSION={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    # ignore:
    #   - goos: darwin
    #     goarch: arm
    #   - goos: darwin
    #     goarch: arm64
    #   - goos: windows
    #     goarch: arm
    #   - goos: windows
    #     goarch: arm64
archives:
  - files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  disable: true
  # name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  disable: true
